# API-first development with OpenAPI
# This file will be used at compile time to generate Spring-MVC endpoint stubs using openapi-generator
openapi: '3.0.1'
info:
  version: 1.0.0
  title: JHipster Store Order API
  license:
    name: Apache2
servers:
  - url: /api/
paths:
  /orders:
    get:
      summary: List all orders with invoice data
      operationId: getDetailedOrders
      tags:
        - orders
      responses:
        '200':
          description: An array of orders enriched with their invoice information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Orders'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Order:
      required:
        - id
        - name
        - invoiceId
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        placedDate:
          type: string
        code:
          type: string
        paymentAmount:
          type: number
        paymentMethod:
          type: string
        paymentStatus:
          type: string
        paymentDate:
          type: string
        invoiceId:
          type: string
    Orders:
      type: array
      items:
        $ref: '#/components/schemas/Order'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
